@section('title', 'Aviso de Privacidad')

@section('content')
<main id="main">

    <!-- ======= Breadcrumbs Section ======= -->
    <section class="breadcrumbs">
        <div class="container">
            <div class="d-flex justify-content-between align-items-center">
                <h2>POLÍTICA DE PRIVACIDAD DE “TAYD IN TIME S. DE R.L.”</h2>
                <ol>
                    <li><a href="/">Inicio</a></li>
                    <li>Aviso de privacidad</li>
                </ol>
            </div>
        </div>
    </section><!-- End Breadcrumbs Section -->

    <section class="inner-page">
        <div class="container">
            <p>
                <br />De conformidad en lo dispuesto por los artículos los artículos 2, 6, 7, 15, 16 y 17 y demás relativos, de la Ley Federal de Protección de Datos Personales en Posesión de Particulares, su Reglamento y normativa relacionada, la empresa “TAYD IN TIME S. DE R.L., hacemos del conocimiento, de nuestros colaboradores, clientes, proveedores, empleados, autoridades, prestadores de servicios y terceros, el compromiso y protección de salvaguardar, sus Datos Personales, emitiendo para tal efecto, el presente Política de Privacidad, en los siguientes términos:
                <br /><br />1.- Nosotros como empresa, mejor conocida como “TAYD”, nombre comercial, es una plataforma web y móvil, que presta servicios de tecnología, responsable de la obtención, uso, divulgación y almacenamiento de los datos personales, (el “Tratamiento”) de los usuarios (“Usted”, el “Titular” o “Usuario”), mismos que se recaban como resultado de los servicios que “TAYD”, presta a través de su página de internet www.tayd.mx/ (el “Sitio”), o bien a través de nuestra aplicación móvil (la “App”), con domicilio en AV. Mario Brown Peralta, número ####, col. Tamulté de las barrancas, c.p. 86035, en la ciudad de Villahermosa, Tabasco, México. “TAYD”, correo electrónico: contacto@tayd.mx , teléfono de contacto: (993) 279-0183. En la plataforma digital virtual, se exhiben y detallan, los servicios de mantenimiento y otros, que serán adquiridos, por los consumidores/usuarios (los “Servicios”).
                <br /><br />2. Datos personales recabados y Tratados por TAYD, para las finalidades indicadas en la presente Política de Privacidad, TAYD no recaba datos personales sensibles.
                <br /><br />3. El trato de los datos personales, serán utilizados, para las siguientes finalidades primarias y necesarias: a).- Ordenar, catalogar, clasificar, dividir o separar y almacenar los datos personales dentro de los sistemas y archivos de “TAYD”, b).- Creación y administración de la cuenta del Usuario, c).- mantener, desarrollar y controlar de la relación comercial entre el Usuario y “TAYD”, d).- Proporcionar al Usuario información necesaria, a través de la página de internet y aplicación, sobre los servicios, para formalizar la relación de consumo de dichos servicios, e).- realizar procesos al interior de “TAYD”, con fines de desarrollo operativo y/o de administración de sistemas dar seguimiento de acuerdo con las necesidades particulares del Usuario, con el fin de brindar los servicios adecuados para cubrir sus necesidades específicas, llevando un registro histórico de la información, con fines de satisfacción al Usuario, desarrollando análisis sobre los intereses y necesidades; brindando de esta manera un mejor servicio, elaboración de prospecciones comerciales y segmentación de mercados, así como las actividades necesarias para gestionar las solicitudes, quejas, y reclamos de los Usuarios, de la empresa o tercero; y direccionarlos a las áreas responsables de emitir las respuestas correspondientes. Sus datos personales, serán utilizados para identificación, operaciones de carácter fiscal, económico, laboral, o administrativo interno, administración de nuestros servicios, análisis de información interna, dar cumplimiento a obligaciones contraídas con usted como Cliente, Proveedor, Empleado, Trabajador, Prestador de Servicio o Tercero, para el ofrecimiento y promoción de bienes, productos y servicios que ofrecemos, gestión contable, económica, fiscal y administrativa de clientes, tener acceso a centrales de riesgo para conocer los estados financieros de los Usuarios, transferencia o transmisión de datos nacional o internacionalmente, a proveedores con los que “TAYD”, desarrolle actividades en cumplimiento de su objeto social. Asimismo, se podrá hacer transferencia, a los aliados estratégicos de la empresa, para que ejecuten actividades de marketing, publicidad y promociones asociadas con el objeto social de nuestra plataforma web y móvil; todo de acuerdo con las disposiciones aplicables.
                <br /><br />4. El Responsable le ofrece, para limitar el uso o divulgación de sus datos personales, en todos aquellos casos legalmente procedentes, usted podrá limitar el uso o divulgación de sus datos personales, dirigiendo la solicitud correspondiente, a nuestro Departamento de Datos Personales, que se ha detallado en el presente Política de privacidad.
                <br /><br />5. Transferencia de sus datos personales, podrán ser transferidos dentro del territorio nacional, conforme a lo siguiente: a solicitud de autoridades, organismos o entidades gubernamentales, en cumplimiento o en relación, con las obligaciones contempladas en la legislación aplicable a TAYD, sus subsidiarias y/o afiliadas, así como en cumplimiento de requerimientos efectuados a las mismas. A compañías afiliadas o subsidiarias de TAYD, con finalidades de valoración y análisis de perfiles de los usuarios, resguardo centralizado de la información y para fines estadísticos y de registro histórico de usuarios del Responsable, sus subsidiarias y/o afiliadas. Las transferencias antes mencionadas, no requieren de su consentimiento conforme a la Legislación de Datos Personales.
                <br /><br />6. En todos aquellos casos legalmente procedentes, usted podrá en todo momento y a través del procedimiento establecido en el presente, ejercer los siguientes derechos referentes a sus datos personales: (i) derechos de Acceso, Rectificación, Cancelación y Oposición (“Derechos ARCO”); (ii) revocar el consentimiento otorgado al Responsable para el tratamiento de sus datos personales; (iii) limitar el uso o divulgación de sus datos personales; y (iv) manifestar su negativa para el tratamiento de sus datos personales con respecto a las finalidades secundarias y accesorias antes mencionadas. Para el ejercicio de dichos derechos referentes a sus datos personales, deberá presentar ante el Responsable, la solicitud correspondiente, mediante un escrito libre debidamente firmado, y dirigido a nuestro Departamento de Datos Personales, entregándolo en el domicilio mencionado en el numeral primero de la presente Política de Privacidad, o enviándolo a la dirección de correo electrónico: contacto@tayd.mx, estableciendo como asunto “Ejercicio de derechos sobre datos personales”. TAYD desea mantener actualizados sus datos personales, en todo momento. Por lo anterior, solicitamos su cooperación, para comunicarnos oportunamente, cualquier cambio que debamos tener en cuenta, para incorporarlo a nuestras bases de datos. Usted garantiza y responde, en cualquier caso, de la veracidad, exactitud, vigencia y autenticidad de los datos personales facilitados para su atención personal, o lo de cualquier tercero bajo su custodia o representación legal.
                <br /><br />7. Le informamos que nuestra Aplicación app móvil y nuestro Sitio web, hacen uso de cookies y otras tecnologías, a través de las cuales es posible monitorear automáticamente su comportamiento como Usuario, brindarle nuestros Servicios y otorgarle una experiencia adecuada, durante el uso de los mismos, así como ofrecerle nuevos productos y servicios basados en sus preferencias. Los datos personales que se recaban a través de estas tecnologías son: dirección IP, sitios web y secciones de los mismos que usted visita desde el Sitio, antes del Sitio o en páginas relacionadas con el Sitio web y la App, características de navegador, características de dispositivos, sistema operativo, preferencias de idiomas, URL a las que se hace referencia, información sobre acciones realizadas en nuestro Sitio y nuestra App, información sobre conductas y acciones realizadas mientras nuestra App está abierta, fechas y horas de las visitas al Sitio o la App, secciones o contenido consultadas en los mismos y datos de ubicación y localización del Usuario mientras nuestra App esté abierta.
                <br /><br />8. El presente Política de Privacidad puede sufrir modificaciones, cambios o actualizaciones derivadas de nuevos requerimientos legales, de nuestras propias necesidades, por los productos o servicios que ofrecemos, de nuestras prácticas de privacidad, de cambios en nuestro modelo de negocio, o por otras causas, dichos cambios se harán del conocimiento de los usuarios de la empresa, a través de correo electrónico en la sección Política de Privacidad El Política de Privacidad constituye un acuerdo válido entre el usuario TAYD IN TIME S.A. DE C.V., (“TAYD”) nombre comercial, si el usuario utiliza los Servicios de la empresa, significa que ha leído, entendido, aceptado y consecuentemente acordado los términos de dicho Política de Privacidad. En caso de que el usuario no esté de acuerdo, con los términos del presente Política de privacidad, no deberá proporcionar ningún tipo de información, ni utilizar los Servicios o cualquier tipo de información relacionada con este sitio web
                <br /><br />9.- Dudas, Quejas y Sugerencias TAYD IN TIME S.A. DE C.V., (“TAYD”) nombre comercial, pone a disposición del usuario el correo electrónico: contacto@tayd.mx, número telefónico: (993) 279-0183, para ponerse en contacto, en caso de presentarse cualquier queja y duda referente a los Servicios. TAYD IN TIME S.A. DE C.V., (“TAYD”), nombre comercial, se reserva el derecho de cambiar, modificar, complementar y/o alterar el presente Política, en cualquier momento, en cuyo caso se hará de su conocimiento, a través de cualquiera de los medios, que establece la legislación en la materia. Para Mayor información consulte la página web: http://inicio.ifai.org.mx/SitePages/ifai.aspx Adicionalmente, en caso de que consideres que tu derecho a la protección de tus Datos Personales ha sido vulnerado, o transgredido te informamos que puedes acudir ante el Instituto Nacional de Transparencia, Acceso a la Información y Protección de Datos Personales (INAI). Para mayor información visita http://inicio.ifal.org.mx Por lo anterior, te entregamos este Política de privacidad, para tu conocimiento.
            </p>
        </div>
    </section>
  </main><!-- End #main -->
@endsection

@include('components.Navbar')
@include('components.Footer')
@include('components.Scripts')
@include('components.Stylesheets')

@extends('components.Main')